version: '3.8'
services:
  db:
    image: postgres:15
    container_name: todo_postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: v3_password  # <-- THAY ĐỔI MẬT KHẨU
      POSTGRES_DB: tododb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_v3:/var/lib/postgresql/data  # <-- THÊM _v2 VÀO ĐÂY

volumes:
  postgres_data_v3: